import { API, clean, normalize, pageUrl, loadManifest, parsePage } from './core-data.js';
const REMOVED_CORES = new Set(['cannibalcore']);
function galleryHeading(doc){return [...doc.querySelectorAll('h2,h3')].find((heading)=>/\bgallery\b/i.test(heading.textContent||'')||heading.querySelector('#Gallery,#gallery'));}
function removeSection(heading){if(!heading)return;const level=Number(heading.tagName.slice(1));let node=heading.nextElementSibling;heading.remove();while(node){const next=node.nextElementSibling;if(/^H[1-6]$/.test(node.tagName)&&Number(node.tagName.slice(1))<=level)break;node.remove();node=next;}}
function removeNotices(doc){const terms=[['sensitive','content','notice'].join(' '),['content','warning'].join(' '),['reason','for','warning'].join(' ')];const selector='p,div,section,aside,blockquote,table,li';[...doc.querySelectorAll(selector)].filter((node)=>{const text=clean(node.textContent).toLowerCase();return text&&text.length<1800&&terms.some((term)=>text.includes(term));}).sort((a,b)=>clean(a.textContent).length-clean(b.textContent).length).forEach((node)=>{if(!node.isConnected)return;const nested=[...node.querySelectorAll(selector)].some((child)=>child!==node&&terms.some((term)=>clean(child.textContent).toLowerCase().includes(term)));if(!nested||node.matches('p,aside,blockquote,table,li'))node.remove();});}
function unwrap(node){node.replaceWith(...node.childNodes);}
function routeLinks(doc){[...doc.querySelectorAll('a')].forEach((link)=>{const href=link.getAttribute('href')||'';if(!href)return unwrap(link);if(href.startsWith('#'))return;let url;try{url=new URL(href,API);}catch{return unwrap(link);}const internal=/(^|\.)fandom\.com$/i.test(url.hostname)||/(^|\.)wikia\.com$/i.test(url.hostname);if(!internal){link.target='_blank';link.rel='noopener noreferrer';return;}const match=decodeURIComponent(url.pathname).match(/^\/wiki\/([^?#]+)$/i);if(!match)return unwrap(link);const title=clean(match[1].replace(/_/g,' '));const namespace=title.includes(':')?title.split(':',1)[0].toLowerCase():'';const excluded=new Set(['file','category','special','template','user','user talk','talk','help','mediawiki','module','portal','blog']);if(!title||excluded.has(namespace)||REMOVED_CORES.has(normalize(title)))return unwrap(link);link.href=pageUrl(title);link.removeAttribute('target');link.removeAttribute('rel');});}
function cleanArticle(html){const doc=new DOMParser().parseFromString(html,'text/html');removeSection(galleryHeading(doc));removeNotices(doc);doc.querySelectorAll('script,style,iframe,object,embed,form,input,button,video,audio,img,picture,source,svg,canvas,table,figure,noscript,.mw-editsection,.portable-infobox,.gallery,.navbox,.toc,.references,.noprint,sup.reference').forEach((node)=>node.remove());routeLinks(doc);doc.querySelectorAll('*').forEach((node)=>[...node.attributes].forEach((attribute)=>{if(node.tagName==='A'&&['href','target','rel'].includes(attribute.name))return;node.removeAttribute(attribute.name);}));doc.querySelectorAll('p,div,section,aside,blockquote').forEach((node)=>{if(!clean(node.textContent)&&!node.querySelector('a'))node.remove();});return doc.body.innerHTML;}
export async function loadCore(title){if(REMOVED_CORES.has(normalize(title)))throw new Error('That Core page is not part of this index.');const [parsed,manifest]=await Promise.all([parsePage(title),loadManifest()]);const canonical=parsed.title||title;const record=manifest.get(normalize(title))||manifest.get(normalize(canonical))||null;if(!record)throw new Error('That Core page is not part of this index.');return{title:record.name,paths:record.paths,article:cleanArticle(parsed.text)};}
