export const API = 'https://aesthetics.fandom.com/api.php';
export const MANIFEST_URL = './assets/cores/manifest.json';
export const clean = (value) => String(value || '').replace(/\s+/g, ' ').trim();
export const normalize = (value) => clean(value).normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/\([^)]*\)/g, '').replace(/[^a-z0-9]+/g, '');
export const escapeHtml = (value) => String(value).replace(/[&<>'"]/g, (character) => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[character]);
const REMOVED_CORES = new Set(['cannibalcore']);
let manifestPromise;
export function pageUrl(title){const url=new URL(location.href);url.search='';url.searchParams.set('core',clean(title));return `${url.pathname}${url.search}`;}
export function assetUrl(path){return String(path).split('/').map(encodeURIComponent).join('/');}
export async function loadManifest(){if(!manifestPromise){manifestPromise=fetch(`${MANIFEST_URL}?v=${Date.now()}`,{cache:'no-store'}).then((response)=>{if(!response.ok)throw new Error('The local gallery index could not be loaded.');return response.json();}).then((manifest)=>{const records=new Map();Object.entries(manifest||{}).forEach(([name,paths])=>{const key=normalize(name);if(REMOVED_CORES.has(key))return;records.set(key,{name,paths:Array.isArray(paths)?paths.filter(Boolean):[]});});return records;});}return manifestPromise;}
async function api(query){const url=new URL(API);Object.entries({format:'json',formatversion:'2',origin:'*',...query}).forEach(([key,value])=>url.searchParams.set(key,value));const response=await fetch(url);if(!response.ok)throw new Error(`Article service returned ${response.status}`);return response.json();}
export async function parsePage(title){if(REMOVED_CORES.has(normalize(title)))throw new Error('That Core page is not part of this index.');let data=await api({action:'parse',page:title,prop:'text|displaytitle',redirects:'1',disabletoc:'1'});if(data?.error||!data?.parse?.text){const search=await api({action:'query',list:'search',srsearch:title,srnamespace:'0',srlimit:'1'});const match=search?.query?.search?.[0]?.title;if(!match)throw new Error('That Core article was not found.');data=await api({action:'parse',page:match,prop:'text|displaytitle',redirects:'1',disabletoc:'1'});}if(data?.error||!data?.parse?.text)throw new Error('That Core article was not found.');return data.parse;}
export async function getStats(){const manifest=await loadManifest();const records=[...manifest.values()].sort((a,b)=>a.name.localeCompare(b.name,undefined,{sensitivity:'base'}));return{records,corePages:records.length,articles:records.length,graphics:records.reduce((sum,record)=>sum+record.paths.length,0),featured:records.find((record)=>normalize(record.name)==='dreamcore')||records[0]||null};}
